#!/bin/bash
#update system packages
sudo pacman -S --needed --noconfirm
sudo pacman --needed --noconfirm -Sy archlinux-keyring
#disabling the full system update to prevent surprise breaks and regressions
#sudo pacman -Syu --needed --noconfirm
