#!/bin/bash

if [[ -n $(pidof joplin-desktop) ]]; then
    echo "Joplin is already running, bringing window to focus now..."
    kp_xwid=$(wmctrl -lp | grep Joplin | grep -Ev '(Chrome|Firefox)' | awk '{print $1}')
    if [[ -z $kp_xwid ]]; then
        echo "No X window ID found. This happens if Joplin is set to minimize to the system tray. Please change your settings."
        exit
    fi
    wmctrl -i -a "$kp_xwid"
else
   echo "Joplin is not running, starting now..."
   nohup joplin-desktop &>/dev/null &
fi
