#!/bin/bash
# Script to automate adding new roms to existing rom folders
# $1 = console, such as psx, n64, etc
if grep -qs "$HOME/mnt/Games" /proc/mounts
then
    echo "NAS already mounted."
else
  sudo mount -v -t cifs '//192.168.1.77/gamer'  ~/mnt/Games -o user=lolguest,vers=2.0,ro
  if grep -qs "$HOME/mnt/Games" /proc/mounts
  then 
      echo "NAS mounted."
  else
      echo "NAS mount error"
      exit
  fi
fi

#Confirm rom folder names match
if [ ! -d ~/mnt/Games/Roms/"$1" ]
then
  echo "The rom folder on NAS doesn't exist. Ensure folder names allign."
  exit 1
fi

if [ ! -d ~/ROMs/"$1" ]
then
  echo "The rom folder on localhost doesn't exist. Ensure folder names allign."
  exit 1
fi

workingDir=~/ROMs/"$1" 
pushd "$workingDir" || exit

#Handle 0merge folder
if [ ! -d ~/mnt/Games/Roms/"$1"/0merge ]
then
  echo "The 0merge directory doesn't exist. Ensure main roms are in 0merge directory."
else
  echo "The 0merge directory was detected."
  rsync -avz --info=progress2 ~/mnt/Games/Roms/"$1"/0merge "$workingDir"

  workingDir=~/ROMs/"$1"/0merge 
  pushd "$workingDir" || exit
  Skyscraper -p "$1" -s esgamelist -i "$workingDir" --flags videos,relative,nosubdirs,unattend --refresh

  #Creds are in config and 0merge was originally scanned via screenscraper so there should be no additions
  Skyscraper -p "$1" -s screenscraper -i "$workingDir" --flags noscreenshots,nocovers,nowheels,nomarquees,nosubdirs,unattend
  Skyscraper -p "$1" -s thegamesdb -i "$workingDir" --flags nosubdirs,unattend

  #May need to add additional Skyscraper commands for retro systems
  #Skycraper blah blah retro

  #Generate new gamelist with ratings and any additional stuff
  Skyscraper -p "$1" -i "$workingDir" --flags unattend,relative

  #Create ES gamelist folder if it doesn't exist
  if [ ! -d ~/ES-DE/gamelists/"$1" ]
  then
    mkdir ~/ES-DE/gamelists/"$1"
    echo "Created ~/ES-DE/gamelists/$1"
  fi

  #Merge new entires into ES gamelist and backup old list
  sed -i '/gameList/d;/xml version/d' "$workingDir"/gamelist.xml
  pushd ~/ES-DE/gamelists/"$1" || exit
  cp gamelist.xml gamelist-backup.xml
  cat gamelist.xml "$workingDir"/gamelist.xml > gamelist-merge.xml
  sed -i '/\/gameList/d;s/\/0merge//' gamelist-merge.xml
  echo "</gameList>" >> gamelist-merge.xml
  mv -f gamelist-merge.xml gamelist.xml

  #Return to 0merge
  popd || exit

  #Move media files from 0merge to ES media
  #Create ES media folder if it doesn't exist
  if [ ! -d ~/ES-DE/downloaded_media/"$1" ]
  then
    mkdir ~/ES-DE/downloaded_media/"$1"
    echo "Created ~/ES-DE/downloaded_media/$1"
  fi
  
  #ESDE-media-move.sh
  #Convert to loop on v2
  cp -r "$workingDir"/media/box2dback/* ~/ES-DE/downloaded_media/"$1"/backcovers
  cp -r "$workingDir"/media/box2dfront/* ~/ES-DE/downloaded_media/"$1"/covers
  cp -r "$workingDir"/media/box3d/* ~/ES-DE/downloaded_media/"$1"/3dboxes
  cp -r "$workingDir"/media/fanart/* ~/ES-DE/downloaded_media/"$1"/fanart
  cp -r "$workingDir"/media/images/* ~/ES-DE/downloaded_media/"$1"/miximages
  cp -r "$workingDir"/media/manual/* ~/ES-DE/downloaded_media/"$1"/manuals
  cp -r "$workingDir"/media/screenshot/* ~/ES-DE/downloaded_media/"$1"/screenshots
  cp -r "$workingDir"/media/screenshottitle/* ~/ES-DE/downloaded_media/"$1"/titlescreens
  cp -r "$workingDir"/media/support/* ~/ES-DE/downloaded_media/"$1"/physicalmedia
  cp -r "$workingDir"/media/videos/* ~/ES-DE/downloaded_media/"$1"/videos
  cp -r "$workingDir"/media/wheel/* ~/ES-DE/downloaded_media/"$1"/marquees
  
  #Clean up 0merge
  #not using $workDir to avoid accidental rm -rf
  rm -rf ~/ROMs/"$1"/0merge/media
  rm -f ~/ROMs/"$1"/0merge/gamelist.*
  
  #Move roms
  mv "$workingDir"/*  ~/ROMs/"$1"/
  
  #Move hidden folders like .multidisc
  mv "$workingDir"/.*  ~/ROMs/"$1"/
  
  #Return to main rom folder
  popd || exit
  
  #Delete 0merge if it doesn't contain any remaining files
  #not using $workDir to avoid accidental rm -rf
  if [ -z "$(ls -A ~/ROMs/"$1"/0merge)" ]
  then
     echo "Deleted 0merge" 
     rm -rf ~/ROMs/"$1"/0merge
  else
     echo "Directory isn't empty, manually inspect and then delete $workingDir"
  fi
  
  #Backup emulationstation dir
  #echo "Run tar backup and temporarily disable suspending/hibernating mid process"
  #nohup sudo -b systemd-inhibit tar -cJvf ~/ESDE-backup.tar.xz ~/ES-DE &>/dev/null
fi

workingDir=~/ROMs/"$1" 

#Handle hacks folder
if [ ! -d ~/mnt/Games/Roms/"$1"/hacks ]
then
  echo "The hacks directory doesn't exist. Ensure hack roms are in hacks directory."
else
  echo "The hacks directory was detected."
  rsync -avz --info=progress2 ~/mnt/Games/Roms/"$1"/hacks "$workingDir" --delete
  rm -f ~/ROMs/"$1"/hacks/gamelist.xml
fi

#remount share as RW
sudo umount  ~/mnt/Games
sudo mount -v -t cifs '//192.168.1.77/gamer'  ~/mnt/Games -o user=gamer,vers=2.0
  
#sync gamelist & media back to NAS
workingDir=~/mnt/Games/Roms/"$1"
pushd "$workingDir" || exit
 
#Clean up 0merge
sudo rm -f "$workingDir"/0merge/gamelist.*
sudo mv "$workingDir"/0merge/* "$workingDir" 
sudo mv "$workingDir"/0merge/.* "$workingDir"
  
#Delete 0merge if it doesn't contain any remaining files
#not using $workDir to avoid accidental rm -rf
if [ -z "$(ls -A ~/mnt/Games/Roms/"$1"/0merge/)" ]
then
   sudo rm -rf ~/mnt/Games/Roms/"$1"/0merge/
   echo "Deleted 0merge" 
else
   echo "Directory isn't empty, manually inspect and then delete $workingDir/0merge/"
fi

#sudo rsync -avz --info=progress2 ~/ESDE-backup.tar.xz ~/mnt/Games/Roms/

#unmount NAS
sudo umount  ~/mnt/Games
