#!/bin/bash
#Need these as jslisten is running as non-user systemd service
#This has proven to be annoying as sometimes the apps are hidden when not specifed
#Despite the launch process being owned by the same user via systemd --user
#export XDG_RUNTIME_DIR=/run/user/1000

if [[ -n $(pidof es-de) ]]; then
    echo "ESDE is already running, bringing window to focus now..."
    kp_xwid=$(wmctrl -lp | grep ES-DE | grep -Ev '(Chrome|Firefox)' | awk '{print $1}')
    if [[ -z $kp_xwid ]]; then
        echo "No X window ID found. This happens if ESDE is set to minimize to the system tray. Please change your settings."
        exit
    fi
    wmctrl -i -a "$kp_xwid"
else
   echo "ESDE is not running, starting now..."
   nohup es-de &>/dev/null &
fi
