#!/bin/bash
 
CUR_DIR=$(pwd)
echo -e "\n\033[1mPulling in latest changes for all repositories...\033[0m\n"
 
cd /opt || exit

GIT_DIRS=$(find . -name ".git" | cut -c 3-)

updateDirs() {
echo ""
echo -e "\033[33m"+"$1"+"\033[0m"
cd "$1" || return
cd ..
git pull --quiet origin master
cd "$CUR_DIR" || return
}

export -f updateDirs

parallel updateDirs ::: "$GIT_DIRS"
                                     
echo -e "\n\033[32m GIT Update Complete!\033[0m\n"
