#!/bin/bash

if [[ -n $(pidof signal-desktop) ]]; then
    echo "Signal is already running, bringing window to focus now..."
    kp_xwid=$(wmctrl -lp | grep $(pidof signal-desktop | awk '{print $NF}') | awk '{print $1}')
    if [[ -z $kp_xwid ]]; then
        echo "No X window ID found. This happens if Signal is set to minimize to the system tray. Please change your settings."
        exit
    fi
    wmctrl -i -a "$kp_xwid"
else
   echo "Signal is not running, starting now..."
   nohup signal-desktop &>/dev/null &
fi
